### ISSUE TITLE
400: We were unable to preform a lookup for 'test.example.com' at this time.; 

### ISSUE THREAD

**Issue by adontz** [linode/linode_api4-python#75] opened 2017-11-16 17:35 UTC
When trying to set rnds property for public IPv4 object I receive the following error:

400: We were unable to preform a lookup for '<my domain name here>' at this time.; 

Can you please explain what does it mean and how am I supposed to fix it?

OFF: It should be "perform" probably, not "preform"

**Comment by Dorthu** [comment] 2017-11-17 20:14
This looks to be an issue on our end - I'm adding it to our internal bug tracker and will update this item when it's been addressed.

**Comment by ravenium** [comment] 2020-02-14 03:27
@Dorthu Has there been any movement on this?  It's absolutely killing some scripting we're trying to do and properly attribute instances.

**Comment by Dorthu** [comment] 2020-02-14 14:05
@ravenium looking through our internal tracker, this was marked as resolved ages ago; I forgot to update the issue here.  Can you paste in an excerpt of the code you're running and the error you're receiving so I can try to reproduce it?

**Comment by ravenium** [comment] 2020-02-14 19:02
@Dorthu Certainly, though now I'm wondering if I am confusing two issues here.  We're trying to stand up an instance, then create both forward (A) and PTR records all in the same script.  I've read elsewhere that you cannot make a PTR record until ~24 hours after creating the instance or A record, is this correct?

Apologies again as I can't seem to find the python I was noodling on, but I did find the terraform (wrong language, but same api backend at least!):


`
resource "linode_instance" "foo" {
   image = "linode/alpine3.9"
   region = "us-west"
   type = "g6-nanode-1"
}
resource "linode_domain_record" "foobar" {
    domain_id = 123456789
    name = "myhost"
    record_type = "A"
    ttl_sec = 300
    target = linode_instance.foo.ip_address
}
resource "linode_rdns" "foo" {
  address = linode_instance.foo.ip_address
  rdns = "${linode_instance.foo.ip_address}.my.domain.name"
}
`

This gets you:

"Error: Error creating a Linode RDNS: [400] We were unable to perform a lookup for '1.2.3.4.my.domain.name' at this time."

(assume my.domain.name is a valid domain name and 1.2.3.4 is the public IP generated by the instance spinup).

**Comment by lgarber-akamai** [comment] 2023-04-18 18:45
Hello @fukawi2, thanks for the feedback!

We have encountered similar issues when trying to automate RDNS in the past. As a workaround, we previously added a `wait_for_available` field to the `linode_rdns` resource in our Terraform Provider (see: https://github.com/linode/terraform-provider-linode/pull/570). 

That said, this issue can definitely be a hindrance to infrastructure automation so I'll be sure to forward your feedback internally.

**Comment by fukawi2** [comment] 2023-04-19 01:50
Ah awesome! I missed that. Thanks for pointing me to it :tada:

**Comment by lgarber-akamai** [comment] 2023-04-19 14:49
I'm closing out this issue since it's not particularly relevant to this repository, but feel free to @ me if you feel this issue is still relevant.

Although we don't have plans to implement a workaround for this issue in this package, you can use the `backoff` package to poll for an RDNS update operation to succeed:

```python
from linode_api4 import LinodeClient, IPAddress, ApiError

client = LinodeClient(os.getenv("LINODE_TOKEN"))


@backoff.on_exception(
    backoff.constant,
    ApiError,
    interval=60,
    max_time=800,
    giveup=lambda e: e.status != 400,
)
def set_rdns_with_retries(ip: IPAddress, hostname: str):
    ip.rdns = hostname
    ip.save()


set_rdns_with_retries(client.load(IPAddress, "127.0.0.1"), "test.example.com")
```

Hope this helps 🙂

**Closed by lgarber-akamai** 2023-04-19 14:49 UTC
